name: CI
on:
  push:
    tags:
      - '*.*.*'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install hatch
        run:
          pip install --upgrade hatch

      - name: Build
        run: hatch build -t wheel

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/flacmirror-*-py3-none-any.whl
          body: ${{ github.ref_name }}

      - name: Publish
        run: hatch publish -y
        env:
          HATCH_INDEX_USER: __token__
          HATCH_INDEX_AUTH: ${{ secrets.PYPI_TOKEN_RELEASE }}